
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class NumericConfigCategory : Singleton<NumericConfigCategory>
    {
        private readonly Dictionary<int, NumericConfig> _dataMap;
        private readonly List<NumericConfig> _dataList;

        public NumericConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, NumericConfig>();
            _dataList = new List<NumericConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                NumericConfig _v;
                _v = global::ET.NumericConfig.DeserializeNumericConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, NumericConfig> DataMap => _dataMap;

        public List<NumericConfig> DataList => _dataList;

        public NumericConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);

        public NumericConfig Get(int key) => _dataMap[key];

        public NumericConfig this[int key] => _dataMap[key];

        partial void PostInit();
    }
}
