
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class NumericConfig : BeanBase
    {
        public NumericConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();
            MaxValue = _buf.ReadFloat();
            DefaultValue = _buf.ReadFloat();

            PostInit();
        }

        public static NumericConfig DeserializeNumericConfig(ByteBuf _buf)
        {
            return new NumericConfig(_buf);
        }

        /// <summary>
        /// 属性类型ID
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 属性名称
        /// </summary>
        public readonly string Name;

        /// <summary>
        /// 最大值上限
        /// </summary>
        public readonly float MaxValue;

        /// <summary>
        /// 默认值
        /// </summary>
        public readonly float DefaultValue;

        public const int __ID__ = -2047312753;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "MaxValue:" + MaxValue + ","
            + "DefaultValue:" + DefaultValue + ","
            + "}";
        }

        partial void PostInit();
    }
}
